Exception in thread "main" java.io.IOException: com.sun.jna.LastErrorException: [5] Input/output error
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.bind(UnixDomainServerSocket.java:136)
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.<init>(UnixDomainServerSocket.java:109)
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.<init>(UnixDomainServerSocket.java:93)
	at mill.main.Server.$anonfun$run$2(MillServerMain.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at mill.main.Server$.lockBlock(MillServerMain.scala:198)
	at mill.main.Server.$anonfun$run$1(MillServerMain.scala:84)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at mill.main.Server$.tryLockBlock(MillServerMain.scala:205)
	at mill.main.Server.run(MillServerMain.scala:81)
	at mill.main.MillServerMain$.main(MillServerMain.scala:45)
	at mill.main.MillServerMain.main(MillServerMain.scala)
Caused by: com.sun.jna.LastErrorException: [5] Input/output error
	at org.scalasbt.ipcsocket.UnixDomainSocketLibrary.bind(Native Method)
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.bind(UnixDomainServerSocket.java:132)
	... 11 more
